{{- if and (eq (.Values.injector.enabled | toString) "true" ) (eq (.Values.injector.networkPolicy.enabled | toString) "true") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "vault.fullname" . }}-agent-injector
  labels:
    app.kubernetes.io/name: {{ template "vault.name" . }}-agent-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault.name" . }}-agent-injector
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: webhook
  ingress:
{{- if .Values.injector.networkPolicy.ingress }}
{{- toYaml .Values.injector.networkPolicy.ingress | nindent 4 }}
{{ end }}
{{ end }}
